name: agrix_mobile
description: A mobile frontend for AgriX - Africa Deep Tech Challenge
HEAD
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

publish_to: 'none'
version: 1.0.0+1
9880f29 (Initial push of AgriX v1 mobile app)

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  http: ^1.1.0
  tflite: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/tflite/crop_disease_model.tflite
    - assets/tflite/labels.txt
