name: agrix_mobile
description: A mobile frontend for AgriX - Africa Deep Tech Challenge
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  http: ^1.1.0
  tflite: ^1.1.2
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/tflite/crop_disease_model.tflite
    - assets/tflite/labels.txt
