# -*- coding: utf-8 -*-
"""qr_scanner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/smwaingeni-ai/AgriX-AfricaDeepTech2025/blob/main/prototype/qr_scanner.ipynb
"""

# STEP 1: Install required package
!pip install opencv-python-headless --quiet

# STEP 2: Import modules
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import os

# STEP 3: Upload a QR image
uploaded = files.upload()
qr_filename = list(uploaded.keys())[0]
qr_image_path = f"/content/{qr_filename}"

# STEP 4: Decode the QR code
def decode_qr(image_path):
    image = cv2.imread(image_path)
    detector = cv2.QRCodeDetector()
    data, points, _ = detector.detectAndDecode(image)
    return data, image, points

# STEP 5: Run and visualize
qr_data, qr_image, qr_points = decode_qr(qr_image_path)

plt.imshow(cv2.cvtColor(qr_image, cv2.COLOR_BGR2RGB))
plt.title("Uploaded QR Image")
plt.axis("off")
plt.show()

# STEP 6: Show result
if qr_data:
    print(f"✅ Decoded QR data: {qr_data}")
else:
    print("⚠️ No QR code detected in the image.")